title: Mikkel Roald-Arbøl
email: mikkel_roald@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':categories/:title/'
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Mikkel Roald-Arbøl # add your name
author-pic: adam-face.jpg
about-author: My name is Mikkel Roald-Arbøl, and I am curious.

# Contact links
email: mikkel_roald@hotmail.com # Add your Email address
phone: +4520320399 # Add your Phone number
website: # Add your website, do not add http://
linkedin: mikkel-roald-arbol # Add your Linkedin handle
github: roaldarbol # Add your Github handle
twitter: # Add your Twitter handle
facebook: # Add your Facebook handle
instagram: roaldarbol # Add your Instagram handle
pinterest: # Add your Pinterest handle

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier: mr-brown # Add your discus identifier

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 10
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: ["_pages"]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]
